name: CI
on:
  push:
    branches:
    - develop
    - main

  pull_request:
    branches:
    - develop
    - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: GitTools
        uses: GitTools/actions@v0.9.13